#!/usr/bin/env python3
import sys
import rclpy
from rclpy.node import Node
from std_srvs.srv import Trigger
import os

from PyQt5 import uic
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtCore import QTimer

class HMIBediening(Node):
    def __init__(self):
        super().__init__('hmi_bediening')
        self.get_logger().info('hmi_bediening node gestart')

        self.start_client = self.create_client(Trigger, '/start_robot')
        self.start_client = self.create_client(Trigger, '/stop_robot')
        self.start_client = self.create_client(Trigger, '/reset_robot')

    def call_service(self, client, name):
        if not client.wait_for_service(timeout_sec=1.0):
            self.get_logger().error(f'Service {name} niet beschikbaar')
            return

        req = Trigger.Request()
        future = client.call_async(req)
        future.add_done_callback(lambda f: self.response_callback(f, name))

    def response_callback(self, future, name):
        try:
            response = future.result()
            self.get_logger().info(f"{name}: success={response.success}, message={response.message}")
        except Exception as e:
            self.get_logger().error(f"Fout bij {name}: {e}")

class HMIWindow(QWidget):
    def __init__(self, ros_node):
        super().__init__()

        self.ros_node = ros_node

        ui_file = os.path.join(
            os.path.dirname(__file__),
            'hmi_window.ui'
        )

        uic.loadUi(ui_file, self)

        self.startButton.clicked.connect(lambda: self.ros_node.call_service(self.ros_node.start_client, 'start_robot'))
        self.stopButton.clicked.connect(lambda: self.ros_node.call_service(self.ros_node.stop_client, 'stop_robot'))
        self.resetButton.clicked.connect(lambda: self.ros_node.call_service(self.ros_node.reset_client, 'reset_robot'))



def main():
    rclpy.init()
    node = HMIBediening()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()