#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from std_srvs.srv import Trigger

class RobotTest(Node):
    def __init__(self):
        super().__init__('robot_test')
        self.create_service(Trigger, '/start_robot', self.start_callback)
        self.create_service(Trigger, '/stop_robot', self.stop_callback)
        self.create_service(Trigger, '/reset_robot', self.reset_callback)
        self.get_logger().info("Robot test services gestart")

    def start_callback(self, request, response):
        response.success = True
        response.message = "Robot gestart"
        return response

    def stop_callback(self, request, response):
        response.success = True
        response.message = "Robot gestopt"
        return response

    def reset_callback(self, request, response):
        response.success = True
        response.message = "Robot gereset"
        return response

def main():
    rclpy.init()
    node = RobotTest()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == "__main__":
    main()